import type {
  BookingDay,
  BookingSlot,
  LanguageOption,
  PaymentMethod,
  Pet,
  RebookSuggestion,
  Service,
  Shop,
  Visit,
} from '@/features/customer/types';

const images = {
  petDash: require('../../../project/shared/images/customer/pet-dash.png'),
  shopAroon: require('../../../project/shared/images/customer/shop-aroon.png'),
  shopFluffRoom: require('../../../project/shared/images/customer/shop-fluff-room.png'),
  shopSoiDog: require('../../../project/shared/images/customer/shop-soi-dog.png'),
  shopBarksBubbles: require('../../../project/shared/images/customer/shop-barks-bubbles.png'),
} as const;

const bookingDays: BookingDay[] = [
  { id: 'mon-11', day: 'Mon', shortLabel: '11', dateLabel: 'Mon 11 Nov' },
  { id: 'tue-12', day: 'Tue', shortLabel: '12', dateLabel: 'Tue 12 Nov' },
  { id: 'wed-13', day: 'Wed', shortLabel: '13', dateLabel: 'Wed 13 Nov' },
  { id: 'thu-14', day: 'Thu', shortLabel: '14', dateLabel: 'Thu 14 Nov' },
  { id: 'fri-15', day: 'Fri', shortLabel: '15', dateLabel: 'Fri 15 Nov' },
  { id: 'sat-16', day: 'Sat', shortLabel: '16', dateLabel: 'Sat 16 Nov', disabled: true },
  { id: 'sun-17', day: 'Sun', shortLabel: '17', dateLabel: 'Sun 17 Nov' },
];

const fullGroom: Service = {
  id: 'full-groom',
  title: 'Full groom',
  description: 'Bath · hand-scissor · nails · ears',
  durationLabel: '75 min',
  durationMinutes: 75,
  price: 650,
  holdAmount: 200,
  requestFee: 50,
  highlightLabel: 'Picked for Dash',
  tags: ['75 min', 'Sensitive-skin shampoo'],
};

const bathAndBlow: Service = {
  id: 'bath-blow',
  title: 'Bath & blow',
  description: 'Shampoo · dry · brush',
  durationLabel: '45 min',
  durationMinutes: 45,
  price: 420,
  holdAmount: 150,
  requestFee: 0,
  tags: ['45 min'],
};

const puppyFirstCut: Service = {
  id: 'puppy-first-cut',
  title: 'Puppy first cut',
  subtitle: 'Mochi',
  description: 'Gentle intro · under 7 mo',
  durationLabel: '60 min',
  durationMinutes: 60,
  price: 550,
  holdAmount: 180,
  requestFee: 0,
  tags: ['60 min'],
};

const instantMorning: BookingSlot[] = [
  { id: '09-00', label: '09:00', durationLabel: '75 min', state: 'available', period: 'morning' },
  { id: '10-30', label: '10:30', durationLabel: '75 min', state: 'available', period: 'morning' },
  { id: '11-15', label: '11:15', durationLabel: '75 min', state: 'available', period: 'morning' },
];

const mixedAfternoon: BookingSlot[] = [
  { id: '13-00', label: '13:00', durationLabel: '75 min', state: 'available', period: 'afternoon' },
  { id: '14-30', label: '14:30', durationLabel: 'confirm', state: 'pending', period: 'afternoon' },
  { id: '15-45', label: '15:45', durationLabel: 'full', state: 'disabled', period: 'afternoon' },
  { id: '16-30', label: '16:30', durationLabel: 'confirm', state: 'pending', period: 'afternoon' },
  { id: '17-15', label: '17:15', durationLabel: 'full', state: 'disabled', period: 'afternoon' },
  { id: '18-00', label: '18:00', durationLabel: '75 min', state: 'available', period: 'afternoon' },
];

export const languageOptions: LanguageOption[] = [
  { id: 'th', label: 'Thai', nativeLabel: 'ภาษาไทย', description: 'ค่าเริ่มต้น' },
  { id: 'en', label: 'English', nativeLabel: 'English', description: 'Pricing shown in THB' },
  { id: 'zh', label: 'Chinese', nativeLabel: '中文', description: 'Simplified · Beta', beta: true },
];

export const customerPets: Pet[] = [
  {
    id: 'dash',
    name: 'Dash',
    breed: 'Welsh Corgi',
    weightLabel: '12.4 kg',
    coat: 'Double · Medium',
    ageLabel: '3 yr 2 mo',
    flags: ['Sensitive skin', 'Fear of clippers', 'Puppy first visit'],
    note: 'Shops use this to quote accurate time and price.',
    photo: images.petDash,
    accent: 'accent',
    nextVisitLabel: 'Tue 10:30',
  },
  {
    id: 'mochi',
    name: 'Mochi',
    breed: 'Poodle mix',
    weightLabel: '8.2 kg',
    coat: 'Curly · Light',
    ageLabel: '7 mo',
    flags: ['Puppy', 'First visit booked'],
    note: 'Still getting used to the dryer sound.',
    photo: images.petDash,
    accent: 'primary',
  },
];

export const customerShops: Shop[] = [
  {
    id: 'aroon',
    name: 'Aroon Grooming',
    nativeName: 'อรุณ กรูมมิ่ง',
    area: 'Saladaeng',
    distanceKm: 0.4,
    rating: 4.9,
    reviewCount: 312,
    heroImage: images.shopAroon,
    image: images.shopAroon,
    heroTitle: 'A small shop that calms nervous dogs',
    intro: 'Five groomers, one waiting dog at a time.',
    detail: 'Dash’s 3rd visit — Pim remembers she prefers slow clippers.',
    confirmLabel: 'Instant confirm',
    confirmMode: 'instant',
    languages: ['EN', 'ไทย', '中文'],
    openHours: 'Open 09:00 – 19:00 · closed Mondays',
    depositPolicy: '฿200 Shield hold, refunded on arrival',
    cancelWindow: 'Free cancel for 24h before the visit',
    trustedNote: 'Returning customers get calmer handoff notes right in the booking flow.',
    staffPreview: ['P', 'N', 'T', '+2'],
    services: [fullGroom, bathAndBlow, puppyFirstCut],
    bookingDays,
    slots: [...instantMorning, ...mixedAfternoon],
  },
  {
    id: 'fluff-room',
    name: 'The Fluff Room',
    area: 'Silom',
    distanceKm: 0.8,
    rating: 4.7,
    reviewCount: 184,
    heroImage: images.shopFluffRoom,
    image: images.shopFluffRoom,
    heroTitle: 'Boutique finishing for pups who need a slower pace',
    intro: 'One-on-one tables and a quiet waiting lane.',
    detail: 'Confirms exception cases within 1 hour.',
    confirmLabel: 'Confirms within 1h',
    confirmMode: 'review',
    languages: ['EN', 'ไทย'],
    openHours: 'Open 10:00 – 20:00 · last walk-in 18:30',
    depositPolicy: '฿150 hold only after the shop accepts',
    cancelWindow: 'Free cancel until 24h before acceptance window ends',
    trustedNote: 'Nothing is charged until the merchant actually accepts the request.',
    staffPreview: ['S', 'A', '+1'],
    services: [
      {
        ...bathAndBlow,
        requestFee: 0,
      },
      {
        ...fullGroom,
        requestFee: 0,
      },
    ],
    bookingDays,
    slots: [
      { id: '14-00', label: '14:00', durationLabel: '45 min', state: 'available', period: 'afternoon' },
      { id: '14-30', label: '14:30', durationLabel: 'confirm', state: 'pending', period: 'afternoon' },
      { id: '15-30', label: '15:30', durationLabel: '45 min', state: 'available', period: 'afternoon' },
      { id: '17-00', label: '17:00', durationLabel: '45 min', state: 'available', period: 'afternoon' },
    ],
  },
  {
    id: 'soi-dog',
    name: 'Soi Dog Studio',
    nativeName: 'ซอยหมา',
    area: 'Silom',
    distanceKm: 1.2,
    rating: 4.8,
    reviewCount: 240,
    heroImage: images.shopSoiDog,
    image: images.shopSoiDog,
    heroTitle: 'Fast, reliable turnaround for repeat regulars',
    intro: 'Known for smooth check-in and no-surprise timing.',
    detail: 'Great backup when you need instant slots later in the day.',
    confirmLabel: 'Instant confirm',
    confirmMode: 'instant',
    languages: ['ไทย', 'EN'],
    openHours: 'Open 09:30 – 19:30 every day',
    depositPolicy: '฿150 Shield hold, released on check-in',
    cancelWindow: 'Free cancel up to 24h before your slot',
    trustedNote: 'Instant slots are held the moment you complete the Shield confirmation.',
    staffPreview: ['B', 'M', '+2'],
    services: [bathAndBlow, fullGroom],
    bookingDays,
    slots: [
      { id: '09-45', label: '09:45', durationLabel: '45 min', state: 'available', period: 'morning' },
      { id: '11-00', label: '11:00', durationLabel: '45 min', state: 'available', period: 'morning' },
      { id: '12-30', label: '12:30', durationLabel: '45 min', state: 'available', period: 'afternoon' },
      { id: '15-15', label: '15:15', durationLabel: '45 min', state: 'available', period: 'afternoon' },
    ],
  },
  {
    id: 'barks-bubbles',
    name: 'Barks & Bubbles',
    area: 'Lumphini',
    distanceKm: 1.7,
    rating: 4.6,
    reviewCount: 129,
    heroImage: images.shopBarksBubbles,
    image: images.shopBarksBubbles,
    heroTitle: 'A dependable neighborhood standby for quick baths',
    intro: 'Good for simple refresh visits and same-week slots.',
    detail: 'Works well as an alternative when a request-confirm shop times out.',
    confirmLabel: 'Same-day slots',
    confirmMode: 'mixed',
    languages: ['EN', 'ไทย'],
    openHours: 'Open 09:00 – 18:00 · closed Tuesdays',
    depositPolicy: 'Small hold only on premium services',
    cancelWindow: 'Free cancel up to 12h before service',
    trustedNote: 'Simple services skip the longer confirmation flow.',
    staffPreview: ['K', 'J'],
    services: [bathAndBlow],
    bookingDays,
    slots: [
      { id: '14-45', label: '14:45', durationLabel: '45 min', state: 'available', period: 'afternoon' },
      { id: '16-15', label: '16:15', durationLabel: '45 min', state: 'available', period: 'afternoon' },
    ],
  },
];

export const paymentMethods: PaymentMethod[] = [
  { id: 'promptpay', title: 'PromptPay', subtitle: 'Fastest · scan & confirm in LINE Pay', kind: 'wallet' },
  { id: 'visa-4412', title: 'Visa •••• 4412', subtitle: 'Hold released automatically', kind: 'card' },
  { id: 'new-card', title: 'Add new card', subtitle: 'Visa · MC · Amex · JCB', kind: 'new' },
];

export const initialVisits: Visit[] = [
  {
    id: 'visit-confirmed',
    shopId: 'aroon',
    petId: 'dash',
    title: 'Aroon Grooming · Tue 12 Nov · 10:30',
    subtitle: 'Dash · Full groom · Shield hold ฿200 · Due ฿500',
    statusLabel: 'Confirmed',
    statusTone: 'confirmed',
    group: 'upcoming',
  },
  {
    id: 'visit-pending',
    shopId: 'fluff-room',
    petId: 'mochi',
    title: 'The Fluff Room · 14:30',
    subtitle: 'Awaiting shop confirm · expires 48m',
    statusLabel: 'Pending',
    statusTone: 'pending',
    group: 'needs-you',
  },
  {
    id: 'visit-past-1',
    shopId: 'aroon',
    petId: 'dash',
    title: 'Aroon Grooming · 18 Oct',
    subtitle: 'Full groom · ฿650 · ★★★★★ rated',
    statusLabel: 'Done',
    statusTone: 'done',
    group: 'past',
  },
  {
    id: 'visit-past-2',
    shopId: 'soi-dog',
    petId: 'dash',
    title: 'Soi Dog Studio · 22 Sep',
    subtitle: 'Bath & blow · ฿420 · rebookable',
    statusLabel: 'Done',
    statusTone: 'done',
    group: 'past',
  },
  {
    id: 'visit-past-3',
    shopId: 'barks-bubbles',
    petId: 'dash',
    title: 'Barks & Bubbles · 12 Aug',
    subtitle: 'Cancelled by you · ฿0 charged',
    statusLabel: 'Cancelled',
    statusTone: 'cancelled',
    group: 'past',
  },
];

export const rebookSuggestion: RebookSuggestion = {
  petId: 'dash',
  shopId: 'aroon',
  serviceId: 'full-groom',
  dateLabel: 'Thu 12 Dec',
  timeLabel: '10:30',
  price: 650,
  holdAmount: 200,
};
